// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Content_screen_init(void)
{
    ui_Content = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContentBack = lv_btn_create(ui_Content);
    lv_obj_set_width(ui_ContentBack, 70);
    lv_obj_set_height(ui_ContentBack, 59);
    lv_obj_set_x(ui_ContentBack, -362);
    lv_obj_set_y(ui_ContentBack, -208);
    lv_obj_set_align(ui_ContentBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContentBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ContentBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContentBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContentBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ContentBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ContentBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_ContentBack);
    lv_img_set_src(ui_Image4, &ui_img_1609717271);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, -1);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 180);

    lv_obj_add_event_cb(ui_ContentBack, ui_event_ContentBack, LV_EVENT_ALL, NULL);

}
