// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Log_screen_init(void)
{
    ui_Log = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogBack = lv_btn_create(ui_Log);
    lv_obj_set_width(ui_LogBack, 70);
    lv_obj_set_height(ui_LogBack, 59);
    lv_obj_set_x(ui_LogBack, -362);
    lv_obj_set_y(ui_LogBack, -208);
    lv_obj_set_align(ui_LogBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LogBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LogBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LogBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_LogBack);
    lv_img_set_src(ui_Image12, &ui_img_1609717271);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, -1);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image12, 180);

    lv_obj_add_event_cb(ui_LogBack, ui_event_LogBack, LV_EVENT_ALL, NULL);

}
