// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Turn_screen_init(void)
{
    ui_Turn = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Turn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button12 = lv_btn_create(ui_Turn);
    lv_obj_set_width(ui_Button12, 70);
    lv_obj_set_height(ui_Button12, 59);
    lv_obj_set_x(ui_Button12, -362);
    lv_obj_set_y(ui_Button12, -208);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDcardBack = lv_img_create(ui_Button12);
    lv_img_set_src(ui_SDcardBack, &ui_img_1609717271);
    lv_obj_set_width(ui_SDcardBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SDcardBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SDcardBack, 0);
    lv_obj_set_y(ui_SDcardBack, -1);
    lv_obj_set_align(ui_SDcardBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SDcardBack, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SDcardBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SDcardBack, 180);

    ui_Mottor1 = lv_btn_create(ui_Turn);
    lv_obj_set_width(ui_Mottor1, 100);
    lv_obj_set_height(ui_Mottor1, 50);
    lv_obj_set_x(ui_Mottor1, 182);
    lv_obj_set_y(ui_Mottor1, -68);
    lv_obj_set_align(ui_Mottor1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Mottor1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Mottor1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Addr1 = lv_label_create(ui_Mottor1);
    lv_obj_set_width(ui_Addr1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Addr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Addr1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Addr1, "Addr1");

    ui_Mottor2 = lv_btn_create(ui_Turn);
    lv_obj_set_width(ui_Mottor2, 100);
    lv_obj_set_height(ui_Mottor2, 50);
    lv_obj_set_x(ui_Mottor2, 182);
    lv_obj_set_y(ui_Mottor2, -157);
    lv_obj_set_align(ui_Mottor2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Mottor2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Mottor2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Addr2 = lv_label_create(ui_Mottor2);
    lv_obj_set_width(ui_Addr2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Addr2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Addr2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Addr2, "Addr2");

    ui_Turn1 = lv_btn_create(ui_Turn);
    lv_obj_set_width(ui_Turn1, 100);
    lv_obj_set_height(ui_Turn1, 50);
    lv_obj_set_x(ui_Turn1, 312);
    lv_obj_set_y(ui_Turn1, -68);
    lv_obj_set_align(ui_Turn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Turn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Turn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Addr3 = lv_label_create(ui_Turn1);
    lv_obj_set_width(ui_Addr3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Addr3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Addr3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Addr3, "Turn1");

    ui_Turn2 = lv_btn_create(ui_Turn);
    lv_obj_set_width(ui_Turn2, 100);
    lv_obj_set_height(ui_Turn2, 50);
    lv_obj_set_x(ui_Turn2, 312);
    lv_obj_set_y(ui_Turn2, -157);
    lv_obj_set_align(ui_Turn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Turn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Turn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Addr5 = lv_label_create(ui_Turn2);
    lv_obj_set_width(ui_Addr5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Addr5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Addr5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Addr5, "Turn2");

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Mottor1, ui_event_Mottor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Mottor2, ui_event_Mottor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Turn1, ui_event_Mottor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Turn2, ui_event_Mottor, LV_EVENT_ALL, NULL);
}
