// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Log_screen_init(void)
{
    ui_Log = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Log, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogBack = lv_btn_create(ui_Log);
    lv_obj_set_width(ui_LogBack, 70);
    lv_obj_set_height(ui_LogBack, 59);
    lv_obj_set_x(ui_LogBack, -362);
    lv_obj_set_y(ui_LogBack, -208);
    lv_obj_set_align(ui_LogBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LogBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LogBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LogBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_LogBack);
    lv_img_set_src(ui_Image12, &ui_img_1609717271);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, -1);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image12, 180);

    ui_Panel10 = lv_obj_create(ui_Log);
    lv_obj_set_width(ui_Panel10, 626);
    lv_obj_set_height(ui_Panel10, 355);
    lv_obj_set_x(ui_Panel10, 5);
    lv_obj_set_y(ui_Panel10, 20);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_btn_create(ui_Panel10);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 209);
    lv_obj_set_y(ui_Button5, 131);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Clear");

    ui_Log1 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log1, -140);
    lv_obj_set_y(ui_Log1, -115);
    lv_obj_set_align(ui_Log1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log1, "NULL");
    lv_obj_set_style_text_font(ui_Log1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Log2 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log2, 152);
    lv_obj_set_y(ui_Log2, -115);
    lv_obj_set_align(ui_Log2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log2, "NULL");
    lv_obj_set_style_text_font(ui_Log2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Log3 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log3, -140);
    lv_obj_set_y(ui_Log3, -70);
    lv_obj_set_align(ui_Log3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log3, "NULL");
    lv_obj_set_style_text_font(ui_Log3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Log4 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log4, 152);
    lv_obj_set_y(ui_Log4, -70);
    lv_obj_set_align(ui_Log4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log4, "NULL");
    lv_obj_set_style_text_font(ui_Log4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Log5 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log5, -140);
    lv_obj_set_y(ui_Log5, -25);
    lv_obj_set_align(ui_Log5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log5, "NULL");
    lv_obj_set_style_text_font(ui_Log5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Log6 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log6, 152);
    lv_obj_set_y(ui_Log6, -25);
    lv_obj_set_align(ui_Log6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log6, "NULL");
    lv_obj_set_style_text_font(ui_Log6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Log7 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log7, -140);
    lv_obj_set_y(ui_Log7, 20);
    lv_obj_set_align(ui_Log7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log7, "NULL");
    lv_obj_set_style_text_font(ui_Log7, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Log8 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log8, 152);
    lv_obj_set_y(ui_Log8, 20);
    lv_obj_set_align(ui_Log8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log8, "NULL");
    lv_obj_set_style_text_font(ui_Log8, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Log9 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log9, -140);
    lv_obj_set_y(ui_Log9, 65);
    lv_obj_set_align(ui_Log9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log9, "NULL");
    lv_obj_set_style_text_font(ui_Log9, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Log10 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Log10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Log10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Log10, 152);
    lv_obj_set_y(ui_Log10, 65);
    lv_obj_set_align(ui_Log10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Log10, "NULL");
    lv_obj_set_style_text_font(ui_Log10, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LogBack, ui_event_LogBack, LV_EVENT_ALL, NULL);

}
