// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

extern uint8_t now_location;

void ui_Show_screen_init(void)
{
    ui_Show = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Show, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button12 = lv_btn_create(ui_Show);
    lv_obj_set_width(ui_Button12, 70);
    lv_obj_set_height(ui_Button12, 59);
    lv_obj_set_x(ui_Button12, -362);
    lv_obj_set_y(ui_Button12, -208);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDcardBack = lv_img_create(ui_Button12);
    lv_img_set_src(ui_SDcardBack, &ui_img_1609717271);
    lv_obj_set_width(ui_SDcardBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SDcardBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SDcardBack, 0);
    lv_obj_set_y(ui_SDcardBack, -1);
    lv_obj_set_align(ui_SDcardBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SDcardBack, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SDcardBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SDcardBack, 180);

    ui_Location = lv_label_create(ui_Show);
    lv_obj_set_width(ui_Location, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Location, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Location, -296);
    lv_obj_set_y(ui_Location, -142);
    lv_obj_set_align(ui_Location, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Location,"当前正对药盒号:%d号",now_location + 1);
    lv_obj_set_style_text_font(ui_Location, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_explain = lv_label_create(ui_Show);
    lv_obj_set_width(ui_explain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_explain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_explain, -20);
    lv_obj_set_y(ui_explain, -40);
    lv_obj_set_align(ui_explain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_explain,
                      "                                       使用说明：\n\n设置时间格式为：xx:xx:xx\n设置服药格式为：x x x x x x (x为数量)\n例如：药盒1服用1颗,药盒2服药2颗,药盒6服用3颗,则设置1 2 0 0 0 3");
    lv_obj_set_style_text_font(ui_explain, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);

}
