// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "bsp_system.h"
///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t *ui_Main;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_TimeLabel;
lv_obj_t *ui_DataLabel;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_MainLabel;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Image9;
void ui_event_SetScreen(lv_event_t *e);
lv_obj_t *ui_SetScreen;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Label3;
void ui_event_ConnentScreen(lv_event_t *e);
lv_obj_t *ui_ConnentScreen;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label5;
void ui_event_SDCardScreen(lv_event_t *e);
lv_obj_t *ui_SDCardScreen;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Label6;
void ui_event_WifiScreen(lv_event_t *e);
lv_obj_t *ui_WifiScreen;
lv_obj_t *ui_Image6;
lv_obj_t *ui_Label7;
void ui_event_UserScreen(lv_event_t *e);
lv_obj_t *ui_UserScreen;
lv_obj_t *ui_Image7;
lv_obj_t *ui_Label8;
void ui_event_LogScreen(lv_event_t *e);
lv_obj_t *ui_LogScreen;
lv_obj_t *ui_Image8;
lv_obj_t *ui_Label9;
// CUSTOM VARIABLES

// SCREEN: ui_Content
void ui_Content_screen_init(void);
lv_obj_t *ui_Content;
void ui_event_ContentBack(lv_event_t *e);
lv_obj_t *ui_ContentBack;
lv_obj_t *ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_WIFI
void ui_WIFI_screen_init(void);
lv_obj_t *ui_WIFI;
void ui_event_WifiBack(lv_event_t *e);
lv_obj_t *ui_WifiBack;
lv_obj_t *ui_Image11;
lv_obj_t *ui_Panel3;
void ui_event_Password(lv_event_t *e);
lv_obj_t *ui_Password;
void ui_event_Users(lv_event_t *e);
lv_obj_t *ui_Users;
lv_obj_t *ui_Login;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Saved;
lv_obj_t *ui_Image10;
lv_obj_t *ui_Image14;
lv_obj_t *ui_WIFI1;
lv_obj_t *ui_Label17;
lv_obj_t *ui_WIFI2;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Label16;
lv_obj_t *ui_WifiBoard;
// CUSTOM VARIABLES

// SCREEN: ui_Log
void ui_Log_screen_init(void);
lv_obj_t *ui_Log;
void ui_event_LogBack(lv_event_t *e);
lv_obj_t *ui_LogBack;
lv_obj_t *ui_Image12;
// CUSTOM VARIABLES

// SCREEN: ui_Turn
void ui_Turn_screen_init(void);
lv_obj_t *ui_Turn;
void ui_event_Button12(lv_event_t *e);
lv_obj_t *ui_Button12;
lv_obj_t *ui_SDcardBack;
lv_obj_t *ui_Mottor1;
lv_obj_t *ui_Addr1;
lv_obj_t *ui_Mottor2;
lv_obj_t *ui_Addr2;
lv_obj_t *ui_Turn1;
lv_obj_t *ui_Addr3;
lv_obj_t *ui_Turn2;
lv_obj_t *ui_Addr5;
// CUSTOM VARIABLES

// SCREEN: ui_Setting
void ui_Setting_screen_init(void);
lv_obj_t *ui_Setting;
void ui_event_Button2(lv_event_t *e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_SDcardBack2;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_User1Set;
lv_obj_t *ui_User1Label;
void ui_event_User1Time1(lv_event_t *e);
lv_obj_t *ui_User1Time1;
void ui_event_User1Time2(lv_event_t *e);
lv_obj_t *ui_User1Time2;
lv_obj_t *ui_Image13;
lv_obj_t *ui_Label1;
void ui_event_User1Time3(lv_event_t *e);
lv_obj_t *ui_User1Time3;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_User1Set2;
lv_obj_t *ui_User1Label2;
lv_obj_t *ui_Image16;
lv_obj_t *ui_Label10;
void ui_event_User2Time1(lv_event_t *e);
lv_obj_t *ui_User2Time1;
void ui_event_User2Time2(lv_event_t *e);
lv_obj_t *ui_User2Time2;
void ui_event_User2Time3(lv_event_t *e);
lv_obj_t *ui_User2Time3;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_User1Set3;
lv_obj_t *ui_User1Label3;
lv_obj_t *ui_Image17;
lv_obj_t *ui_Label15;
void ui_event_User3Time1(lv_event_t *e);
lv_obj_t *ui_User3Time1;
void ui_event_User3Time2(lv_event_t *e);
lv_obj_t *ui_User3Time2;
void ui_event_User3Time3(lv_event_t *e);
lv_obj_t *ui_User3Time3;
lv_obj_t *ui_TimeKeyboard;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SetScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Setting, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Setting_screen_init);
    }
}

void ui_event_ConnentScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Content, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Content_screen_init);
    }
}

void ui_event_SDCardScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Turn, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Turn_screen_init);
    }
}

void ui_event_WifiScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_WIFI, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_WIFI_screen_init);
    }
}

void ui_event_UserScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Content, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Content_screen_init);
    }
}

void ui_event_LogScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Log, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Log_screen_init);
    }
}

void ui_event_ContentBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}

void ui_event_WifiBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}

void ui_event_Password(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_keyboard_set_target(ui_WifiBoard, ui_Password);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_WifiBoard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_WifiBoard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Users(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_WifiBoard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_keyboard_set_target(ui_WifiBoard, ui_Users);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_WifiBoard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_LogBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}

void ui_event_Button12(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}


void ui_event_Mottor(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *targer = lv_event_get_target(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        if (targer == ui_Mottor1)
        {


        }
        else if (targer == ui_Mottor2)
        {

        }
        else if (targer == ui_Turn1)
        {
            motorTop_turn ^= 1;

        }
        else if (targer == ui_Turn2)
        {

            motorBottom_turn ^= 1;
        }
    }
}

void ui_event_Button2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}

void ui_event_User1Time1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User1Time1);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User1Time2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User1Time2);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User1Time3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User1Time3);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User2Time1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User2Time1);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User2Time2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User2Time2);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User2Time3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User2Time3);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User3Time1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User3Time1);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User3Time2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User3Time2);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User3Time3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User3Time3);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_Content_screen_init();
    ui_WIFI_screen_init();
    ui_Log_screen_init();
    ui_Turn_screen_init();
    ui_Setting_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
