// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "bsp_system.h"
///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t *ui_Main;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_TimeLabel;
lv_obj_t *ui_DataLabel;
lv_obj_t *ui_Data;
lv_obj_t *ui_Image15;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Temp;
lv_obj_t *ui_Humidity;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_MainLabel;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Image9;
void ui_event_SetScreen(lv_event_t *e);
lv_obj_t *ui_SetScreen;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Label3;
void ui_event_ConnentScreen(lv_event_t *e);
lv_obj_t *ui_ConnentScreen;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label5;
void ui_event_SDCardScreen(lv_event_t *e);
lv_obj_t *ui_SDCardScreen;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Label6;
void ui_event_WifiScreen(lv_event_t *e);
lv_obj_t *ui_WifiScreen;
lv_obj_t *ui_Image6;
lv_obj_t *ui_Label7;
lv_obj_t *ui_UserScreen;
lv_obj_t *ui_Image7;
lv_obj_t *ui_Label8;
void ui_event_LogScreen(lv_event_t *e);
lv_obj_t *ui_LogScreen;
lv_obj_t *ui_Image8;
lv_obj_t *ui_Label9;
// CUSTOM VARIABLES

// SCREEN: ui_Content
void ui_Content_screen_init(void);
lv_obj_t *ui_Content;
void ui_event_ContentBack(lv_event_t *e);
lv_obj_t *ui_ContentBack;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_yh1;
lv_obj_t *ui_yh2;
lv_obj_t *ui_yh3;
lv_obj_t *ui_yh4;
lv_obj_t *ui_yh5;
lv_obj_t *ui_yh6;
// CUSTOM VARIABLES

// SCREEN: ui_WIFI
void ui_WIFI_screen_init(void);
lv_obj_t *ui_WIFI;
void ui_event_WifiBack(lv_event_t *e);
lv_obj_t *ui_WifiBack;
lv_obj_t *ui_Image11;
lv_obj_t *ui_Panel3;
void ui_event_Password(lv_event_t *e);
lv_obj_t *ui_Password;
void ui_event_Users(lv_event_t *e);
lv_obj_t *ui_Users;
lv_obj_t *ui_Login;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Saved;
lv_obj_t *ui_Image10;
lv_obj_t *ui_Image14;
lv_obj_t *ui_WIFI1;
lv_obj_t *ui_Label17;
lv_obj_t *ui_WIFI2;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Label16;
lv_obj_t *ui_WifiBoard;
void ui_login_event(lv_event_t *e);
// CUSTOM VARIABLES

// SCREEN: ui_Log
void ui_Log_screen_init(void);
lv_obj_t *ui_Log;
void ui_event_LogBack(lv_event_t *e);
lv_obj_t *ui_LogBack;
lv_obj_t *ui_Image12;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Button5;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Log1;
lv_obj_t *ui_Log2;
lv_obj_t *ui_Log3;
lv_obj_t *ui_Log4;
lv_obj_t *ui_Log5;
lv_obj_t *ui_Log6;
lv_obj_t *ui_Log7;
lv_obj_t *ui_Log8;
lv_obj_t *ui_Log9;
lv_obj_t *ui_Log10;
// CUSTOM VARIABLES

// SCREEN: ui_Show
void ui_Show_screen_init(void);
lv_obj_t *ui_Show;
void ui_event_Button12(lv_event_t *e);
lv_obj_t *ui_Button12;
lv_obj_t *ui_SDcardBack;
lv_obj_t *ui_Location;
lv_obj_t *ui_explain;
// CUSTOM VARIABLES

// SCREEN: ui_Setting
void ui_Setting_screen_init(void);
lv_obj_t *ui_Setting;
void ui_event_Button2(lv_event_t *e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_SDcardBack2;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_User1Set;
lv_obj_t *ui_User1Label;
void ui_event_User1Time1(lv_event_t *e);
lv_obj_t *ui_User1Time1;
void ui_event_User1Time2(lv_event_t *e);
lv_obj_t *ui_User1Time2;
lv_obj_t *ui_Image13;
lv_obj_t *ui_Label1;
void ui_event_User1Time3(lv_event_t *e);
lv_obj_t *ui_User1Time3;
void ui_event_User1eat1(lv_event_t *e);
lv_obj_t *ui_User1eat1;
void ui_event_User1eat3(lv_event_t *e);
lv_obj_t *ui_User1eat3;
void ui_event_User1eat2(lv_event_t *e);
lv_obj_t *ui_User1eat2;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_User2Set;
lv_obj_t *ui_User1Label2;
lv_obj_t *ui_Image16;
lv_obj_t *ui_Label10;
void ui_event_User2Time1(lv_event_t *e);
lv_obj_t *ui_User2Time1;
void ui_event_User2Time2(lv_event_t *e);
lv_obj_t *ui_User2Time2;
void ui_event_User2Time3(lv_event_t *e);
lv_obj_t *ui_User2Time3;
void ui_event_User2eat1(lv_event_t *e);
lv_obj_t *ui_User2eat1;
void ui_event_User2eat2(lv_event_t *e);
lv_obj_t *ui_User2eat2;
void ui_event_User2eat3(lv_event_t *e);
lv_obj_t *ui_User2eat3;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_User3Set;
lv_obj_t *ui_User1Label3;
lv_obj_t *ui_Image17;
lv_obj_t *ui_Label15;
void ui_event_User3Time1(lv_event_t *e);
lv_obj_t *ui_User3Time1;
void ui_event_User3Time2(lv_event_t *e);
lv_obj_t *ui_User3Time2;
void ui_event_User3Time3(lv_event_t *e);
lv_obj_t *ui_User3Time3;
void ui_event_Usere3eat1(lv_event_t *e);
lv_obj_t *ui_User3eat1;
void ui_event_User3eat2(lv_event_t *e);
lv_obj_t *ui_User3eat2;
void ui_event_User3eat3(lv_event_t *e);
lv_obj_t *ui_User3eat3;
lv_obj_t *ui_TimeKeyboard;
void ui_event_set(lv_event_t *e);

// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SetScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Setting, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Setting_screen_init);
    }
}

void ui_event_ConnentScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Content, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Content_screen_init);
    }
}

void ui_event_SDCardScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Show, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Show_screen_init);
    }
}

void ui_event_WifiScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_WIFI, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_WIFI_screen_init);
    }
}

void ui_event_LogScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Log, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Log_screen_init);
    }
}

void ui_event_ContentBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}

void ui_event_WifiBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}

void ui_event_Password(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_keyboard_set_target(ui_WifiBoard, ui_Password);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_WifiBoard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_WifiBoard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Users(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_WifiBoard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_keyboard_set_target(ui_WifiBoard, ui_Users);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_WifiBoard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

char wifi_name[20];
char wifi_pass[20];
uint8_t login_flag = 0;
lv_obj_t *login_test;
void ui_login_event(lv_event_t *e)
{
    lv_obj_t *taget = lv_event_get_target(e);

    if (taget == ui_Login)
    {
        if (login_flag == 0)
        {
            lv_obj_t *box = lv_msgbox_create(ui_WIFI, "Login Message", NULL, NULL, true);
            lv_obj_set_size(box, 350, 200);
            lv_obj_center(box);
            login_test = lv_label_create(box);
            lv_obj_set_style_text_font(login_test, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(login_test, "\n       Wait for login in...");
            sprintf((char *)wifi_name, lv_textarea_get_text(ui_Users));
            sprintf((char *)wifi_pass, lv_textarea_get_text(ui_Password));
            ESP8266_Clear();
            login_flag = 1;
        }

        // printf("\"AT+CWJAP=\"%s\",\"%s\"\r\n\"", wifi_name, wifi_pass);
        //  lv_label_set_text(login_test,"\n        Login success!");
    }
    if (taget == ui_WIFI1)
    {
        lv_textarea_set_text(ui_Users, "CMCC");
        lv_textarea_set_text(ui_Password, "danpanji123321");
    }
    if (taget == ui_WIFI2)
    {
        lv_textarea_set_text(ui_Users, "Steam32");
        lv_textarea_set_text(ui_Password, "1594568830");
    }
}

void ui_event_LogBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}

void ui_event_Button12(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}

void ui_event_Button2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Main_screen_init);
    }
}

void ui_event_User1Time1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User1Time1);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User1Time2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User1Time2);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User1Time3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User1Time3);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User1eat1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User1eat1);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User1eat3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User1eat3);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User1eat2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User1eat2);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User2Time1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User2Time1);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User2Time2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User2Time2);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User2Time3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User2Time3);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User2eat1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User2eat1);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User2eat2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User2eat2);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User2eat3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User2eat3);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User3Time1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User3Time1);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User3Time2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User3Time2);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User3Time3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User3Time3);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Usere3eat1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User3eat1);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User3eat2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User3eat2);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_User3eat3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_TimeKeyboard, ui_User3eat3);
    }
    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_TimeKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void timeGet(int *timeBuff, const char *Time)
{
    char str[20];
    sprintf(str, Time);
    // printf("str: %s\n", str);
    char *p = str;
    while (*p != '\0')
    {
        if (*p == ':')
        {
            *p = ' ';
        }
        p++;
    }
    sscanf(str, "%d %d", &timeBuff[0], &timeBuff[1]);
}

void eatGet(int *eatBuff, const char *Eat)
{
    sscanf(Eat, "%d %d %d %d %d %d", &eatBuff[0], &eatBuff[1], &eatBuff[2], &eatBuff[3], &eatBuff[4], &eatBuff[5]);
}

void ui_event_set(lv_event_t *e)
{
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *box = lv_msgbox_create(ui_Setting, "Setting Message", NULL, NULL, true);
    lv_obj_set_size(box, 350, 200);
    lv_obj_center(box);
    lv_obj_t *set_test = lv_label_create(box);
    lv_obj_set_style_text_font(set_test, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(set_test, "\n       Setting success!");
    // HAL_GPIO_TogglePin(LED0_GPIO_Port, LED0_Pin);
    if (target == ui_User1Set)
    {
        timeGet(user_messages[0].Time[0], lv_textarea_get_text(ui_User1Time1));
        timeGet(user_messages[0].Time[1], lv_textarea_get_text(ui_User1Time2));
        timeGet(user_messages[0].Time[2], lv_textarea_get_text(ui_User1Time3));
        eatGet(user_messages[0].medicine[0], lv_textarea_get_text(ui_User1eat1));
        eatGet(user_messages[0].medicine[1], lv_textarea_get_text(ui_User1eat2));
        eatGet(user_messages[0].medicine[2], lv_textarea_get_text(ui_User1eat3));

        for (int i = 0; i < 3; i++)
        {
            printf("%d %d\r\n", user_messages[0].Time[i][0], user_messages[0].Time[i][1]);
            printf("%d %d %d %d %d %d\r\n", user_messages[0].medicine[i][0], user_messages[0].medicine[i][1], user_messages[0].medicine[i][2], user_messages[0].medicine[i][3], user_messages[0].medicine[i][4], user_messages[0].medicine[i][5]);
        }
    }
    if (target == ui_User2Set)
    {
        timeGet(user_messages[1].Time[0], lv_textarea_get_text(ui_User2Time1));
        timeGet(user_messages[1].Time[1], lv_textarea_get_text(ui_User2Time2));
        timeGet(user_messages[1].Time[2], lv_textarea_get_text(ui_User2Time3));
        eatGet(user_messages[1].medicine[0], lv_textarea_get_text(ui_User2eat1));
        eatGet(user_messages[1].medicine[1], lv_textarea_get_text(ui_User2eat2));
        eatGet(user_messages[1].medicine[2], lv_textarea_get_text(ui_User2eat3));
    }
    if (target == ui_User3Set)
    {
        timeGet(user_messages[2].Time[0], lv_textarea_get_text(ui_User3Time1));
        timeGet(user_messages[2].Time[1], lv_textarea_get_text(ui_User3Time2));
        timeGet(user_messages[2].Time[2], lv_textarea_get_text(ui_User3Time3));
        eatGet(user_messages[2].medicine[0], lv_textarea_get_text(ui_User3eat1));
        eatGet(user_messages[2].medicine[1], lv_textarea_get_text(ui_User3eat2));
        eatGet(user_messages[2].medicine[2], lv_textarea_get_text(ui_User3eat3));
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_Content_screen_init();
    ui_WIFI_screen_init();
    ui_Log_screen_init();
    ui_Show_screen_init();
    ui_Setting_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
